### ISSUE TITLE
Executable file for windows is not working

### ISSUE THREAD

**Issue by a0ali0taha** [karim-bouchez/moubah#6]
Salam
I downloaded the Windows version, and it crashed, not open at all.
windows 10

**Comment by a0ali0taha** [comment]
not working in mac m1 as well
<img width="248" alt="image" src="https://github.com/itkho/moubah/assets/2883928/a5057bbe-cff8-4ffb-b4c7-609a47ef9db2">

**Comment by karim-bouchez** [comment]
Wa 3alayka as salam @a0ali0taha 

- **As for the Mac M1 app**, it's because of an Apple security.
The app isn't really damaged, but it's because the app isn't verified by apple and I didn't signed it with an Apple developer account.
You can run for exemple the command on the section 4 [here](https://osxdaily.com/2019/02/13/fix-app-damaged-cant-be-opened-trash-error-mac/) : 
`xattr -d com.apple.quarantine /Path/To/Moubah.app`

- **As for the Windows app**, you should have some log files in the following directory : 
`C:\Users\<YOUR_NAME>\AppData\Roaming\Moubah\logs`
Can you please check for them and copy them here to see if something is missing ?

**Comment by karim-bouchez** [comment]
I forgot to mention that for Mac M1 (and higher) you will need to download [Python 3.8.10](https://www.python.org/downloads/release/python-3810/)

**Comment by a0ali0taha** [comment]
Thanks @karim-bouchez for your reply
the GUI is working now, but still the server is not working on MAC
<img width="945" alt="image" src="https://github.com/itkho/moubah/assets/2883928/8b253dae-37cc-4baa-917c-1a5b452a112c">

**Comment by karim-bouchez** [comment]
Oh, you don't have to install it on your own @a0ali0taha 
the installation guide is just if you need a development environment

If you have correctly installed [Python 3.8.10](https://www.python.org/downloads/release/python-3810/), you should have logs in: `/Users/<USER>/Library/Logs/Moubah`
